FROM python:3.11-slim

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir PyYAML

COPY feed.py /usr/bin/feed.py
CMD ["python", "/usr/bin/feed.py"]
